apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: schema-registry
  name: schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: schema-registry
    spec:
      containers:
      - env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: schema-registry
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: zookeeper:32181
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://0.0.0.0:8081
        image: confluentinc/cp-schema-registry:5.3.2
        name: schema-registry
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
      # don't publish environment variables with port information so that the confluent scripts don't get confused
      enableServiceLinks: false
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: schema-registry
  name: schema-registry
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app: schema-registry
status:
  loadBalancer: {}