apiVersion: apps/v1
kind: Deployment
metadata:
  name: scylladb
  labels:
    app: scylladb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scylladb
  template:
    metadata:
      labels:
        app: scylladb
    spec:
      containers:
        - name: scylla
          image: scylladb/scylla
          imagePullPolicy: IfNotPresent
          #args: ["--seeds", "scylla-0.scylla.default.svc.cluster.local"]
          args: ["--listen-address", "0.0.0.0", "--broadcast-rpc-address", "scylladb" ]
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          # resources:
          #   limits:
          #     memory: 1Gi
          #   requests:
          #     memory: 1Gi
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "PID=$(pidof scylla) && kill $PID && while ps -p $PID > /dev/null; do sleep 1; done"]
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - exec
                - /opt/ready-probe.sh
            initialDelaySeconds: 15
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: scylladb
spec:
  selector:
    app: scylladb
  ports:
    - protocol: TCP
      name: "9042"
      port: 9042
      targetPort: 9042
    - protocol: TCP
      name: "9160"
      port: 9160
      targetPort: 9160