apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: generator-microservice
  name: generator-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator-microservice
  strategy: {}
  template:
    metadata:
      labels:
        app: generator-microservice
    spec:
      containers:
      - image: oscarrenalias/generator-microservice
        name: generator
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: generator-microservice
spec:
  selector:
    app: generator-microservice
  ports:
    - protocol: TCP
      name: "8080"
      port: 8080
      targetPort: 8080