apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: generator-microservice

build:
  artifacts:
  - image: oscarrenalias/generator-microservice
    jib: {}

deploy:
  kubectl:
    manifests:
    - k8s/app.yaml