apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: topology-microservice

build:
  artifacts:
  - image: accenture/topology-microservice
    jib: {}

deploy:
  kubectl:
    manifests:
    - k8s/app.yaml